sequenceDiagram
    participant User
    participant App
    participant Server
    User->>+App: Ingresar a la opción de restablecimiento de contraseña
    App->>+Server: Enviar solicitud de restablecimiento de contraseña
    Server->>+User: Enviar correo electrónico de restablecimiento de contraseña con un enlace único
    User->>+App: Abrir el enlace único del correo electrónico
    App->>+Server: Solicitar token de restablecimiento de contraseña
    Server->>+App: Enviar token de restablecimiento de contraseña
    App->>+User: Pedir al usuario que ingrese un nueva contraseña y el token
    User->>+App: Ingresar una nueva contraseña y el token recibido
    App->>+Server: Enviar nueva contraseña y token de restablecimiento de contraseña
    Server->>+User: Confirmar el cambio de contraseña y restablecimiento de la cuenta
    App->>+User: Mostrar mensaje de confirmación de restablecimiento de contraseña

